displayName: AB Testing Middleware
type: middleware
import: github.com/daemonp/traefik-forklift-middleware
summary: A middleware for A/B testing in Traefik
testData:
  V1Backend: "http://v1-backend.example.com"
  V2Backend: "http://v2-backend.example.com"
  Rules:
    - Path: "/test"
      Method: "GET"
      Backend: "http://v1-backend.example.com"
      Percentage: 50
