version: '3'

# https://github.com/traefik/traefik/issues/9512
# There is an issue pulling the plugin in new versions
services:
  traefik:
    image: traefik:v2.8.3
    #image: traefik:v3.1.2
    environment:
      DEBUG: true
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
        #- "--experimental.Plugins.abtest.moduleName=github.com/daemonp/forklift"
        #- "--experimental.plugins.abtest.version=v0.1.6"
      #- "--experimental.plugins.example.modulename=github.com/traefik/plugindemo"
      #- "--experimental.plugins.example.version=v0.2.2"
      - "--experimental.localPlugins.abtest.moduleName=github.com/daemonp/forklift"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/plugins-local/src/github.com/daemonp/forklift
    labels:
      - "traefik.enable=true"

  echo1:
    image: hashicorp/http-echo
    command: ["-text", "Hello from V1"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.echo1.loadbalancer.server.port=5678"

  echo2:
    image: hashicorp/http-echo
    command: ["-text", "Hello from V2"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.echo2.loadbalancer.server.port=5678"

  echo3:
    image: hashicorp/http-echo
    command: ["-text", "Hello from V3"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.echo3.loadbalancer.server.port=5678"

  echo4:
    image: hashicorp/http-echo
    command: ["-text", "Hello from V4"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.echo4.loadbalancer.server.port=5678"

  echo5:
    image: hashicorp/http-echo
    command: ["-text", "Hello from V5"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.echo5.loadbalancer.server.port=5678"

  echo6:
    image: hashicorp/http-echo
    command: ["-text", "Hello from V6"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.echo6.loadbalancer.server.port=5678"

  echo7:
    image: hashicorp/http-echo
    command: ["-text", "Hello from V7"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.echo7.loadbalancer.server.port=5678"

  abtest:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.abtest.rule=PathPrefix(`/`)"
      - "traefik.http.routers.abtest.entrypoints=web"
      - "traefik.http.routers.abtest.middlewares=abtest-middleware"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.defaultBackend=http://echo1:5678"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[0].path=/"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[0].method=GET"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[0].backend=http://echo1:5678"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[0].weight=1"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[1].path=/"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[1].method=GET"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[1].backend=http://echo2:5678"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[1].weight=1"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[2].path=/"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[2].method=GET"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[2].backend=http://echo3:5678"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[2].weight=1"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[3].path=/"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[3].method=GET"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[3].backend=http://echo4:5678"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[3].weight=1"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[4].path=/"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[4].method=GET"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[4].backend=http://echo5:5678"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[4].weight=1"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[5].path=/"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[5].method=GET"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[5].backend=http://echo6:5678"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[5].weight=1"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[6].path=/"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[6].method=GET"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[6].backend=http://echo7:5678"
      - "traefik.http.middlewares.abtest-middleware.plugin.abtest.rules[6].weight=1"
